name: Unified Python Workflow

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-all-scripts:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python dependencies from private repo
        run: |
          pip install -r private_py/requirements.txt

      # ---------------- V Section ----------------
      - name: Run datatxt.py
        run: python private_py/vavoo/datatxt.py

      - name: Run datatxtm3u.py
        run: python private_py/vavoo/vavooiptvm3u.py

      # - name: Run sporekrani.py
      #   run: python private_py/vavoo/sporekrani.py

      # - name: Run spor_ekrani_m3u.py
      #   run: python private_py/vavoo/spor_ekrani_m3uyeni.py

      # ---------------- D Section ----------------
      # - name: Run schedule_aljson.py
      #   run: python private_py/channels/daddylive/event/schedule_aljson.py

      # - name: Run server_key_schedule.py
      #   run: python private_py/channels/daddylive/event/server_key_schedule.py

      # - name: Run schedule_son.py
      #   run: python private_py/channels/daddylive/event/schedule_son.py

      # - name: Run eventm3u.py
      #   run: python private_py/channels/daddylive/event/eventm3uprox.py

      # - name: Run convertm3u.py
      #   run: python private_py/channels/daddylive/event/convertm3u.py

      # ---------------- Kanal Section ----------------
      # - name: Run kanal_verileri.py
      #   run: python private_py/daddylivekanal/kanal_verileri.py

      # - name: Run server_key_kanal.py
      #   run: python private_py/daddylivekanal/server_key_kanal.py

      # - name: Run kanal_birlestir.py
      #   run: python private_py/daddylivekanal/kanal_birlestir.py

      # - name: Run kanalm3u.py
      #   run: python private_py/daddylivekanal/kanalm3uprox.py

      # ---------------- S Section ----------------
      # - name: Run ana_domain.py
      #   run: python private_py/selcuk/ana_domain.py

      # - name: Run baseurl.py
      #   run: python private_py/selcuk/baseurl.py

      # - name: Run encode.py
      #   run: python private_py/selcuk/encode.py

      # - name: Run m3u.py
      #   run: python private_py/selcuk/m3uyeni.py

      # ---------------- STEP: Copy .m3u Files to m3u8file Repo ----------------
      - name: Clone m3u8file Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/m3u8file.git m3u8file_repo

      - name: Copy all .m3u files to m3u8file Repo (root)
        run: |
          find d s v sdizi -type f -name "*.m3u" -exec cp {} m3u8file_repo/ \; || echo "No .m3u files found"

      - name: Commit and Push to m3u8file Repo
        run: |
          cd m3u8file_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.m3u
          git commit -m "Unified workflow .m3u dosyaları eklendi [auto]" || echo "No changes"
          git pull --rebase origin main || echo "No upstream changes"
          git push origin main
