name: Run RecTV Script (M3U Generator)

on:
  workflow_dispatch:
//  schedule:
//    - cron: '30 */2 * * *'

jobs:
  generate-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests aiohttp aiofiles

      - name: Run RecTV Script
        run: python private_py/rectv/rectv.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Set remote URL
        run: git remote set-url origin https://github.com/zerodayip/sitem3u.git

      - name: Commit and Push M3U Files
        run: |
          git add r/main.m3u r/dizi.m3u
          git commit -m "Update r/main.m3u and r/dizi.m3u via RecTV workflow" || echo "No changes to commit"
          git push origin main
