name: Run RecTV Script

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */3 * * *' # İsteğe bağlı zamanlama

jobs:
  run-rectv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp aiofiles requests

      - name: Run RecTV Script
        run: python private_py/rectv/rectv.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push
        run: |
          git add r/main.m3u r/dizi.m3u
          git commit -m "Auto update M3U files from RecTV" || echo "No changes to commit"
          git push origin main
