name: Run RecTV Script

on:
  workflow_dispatch:

jobs:
  run-rectv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp aiofiles requests

      - name: Run RecTV Script
        run: python private_py/rectv/rectv.py

      - name: Create m3u8 folder in Py repo and copy M3U files
        run: |
          mkdir -p private_py/m3u8
          cp r/main.m3u private_py/m3u8/
          cp r/dizi.m3u private_py/m3u8/

      - name: Check copied files
        run: |
          echo "Dosyalar kopyalandı:"
          ls private_py/m3u8

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push copied M3U files to Py repo
        run: |
          cd private_py
          git add m3u8/main.m3u m3u8/dizi.m3u
          git commit -m "RecTV'den çıkan M3U dosyaları m3u8 klasörüne kopyalandı [auto]" || echo "No changes"
          git push origin main
