name: Run RecTV Script

on:
  workflow_dispatch:

jobs:
  run-rectv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo (sitem3u)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp aiofiles requests

      - name: Run RecTV Script
        run: python private_py/rectv/rectv.py

      # ✅ Public repoya push
      - name: Commit and Push to Public Repo (sitem3u)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add r/main.m3u r/dizi.m3u
          git commit -m "RecTV: public repoda güncellendi [auto]" || echo "No changes"
          git push origin main

      # ✅ Private Py repo içine kopyalama
      - name: Copy files to private_py/m3u8
        run: |
          mkdir -p private_py/m3u8
          cp r/main.m3u private_py/m3u8/ || echo "main.m3u kopyalanamadı"
          cp r/dizi.m3u private_py/m3u8/ || echo "dizi.m3u kopyalanamadı"

      - name: Check copied files
        run: |
          echo "📁 Kopyalanan dosyalar:"
          ls -lh private_py/m3u8

      # ✅ Private Py repo'ya push
      - name: Commit and Push to Private Py Repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add m3u8/main.m3u m3u8/dizi.m3u
          git commit -m "RecTV çıktıları m3u8 klasörüne eklendi [auto]" || echo "No changes"
          git push origin main
